# Site settings
title: Corali Almanza
description: Apasionada por la tecnología
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: coralidiana
user_description: Corali Almanza es Licenciada en Informática, mención Ingeniería de Sistemas. Desarrolladora Web en Satva SRL. Instructora de Scratch en The It Club. Actualmente pertenece al programa internacional GitHub Campus Expert. Organizadora de la comunidad Kotlin La Paz. Actual organizadora de la conferencia internacional mDevConf 2021, apasionada por las tecnologías Web .
user_title: Web Developer | GitHub Campus Expert 
email: dianalmanza20@gmail.com
twitter_username: coralidiana1
github_username:  coralidiana
facebook_username: coralidianaa
instagram_username: coralialmanza

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
